### ISSUE TITLE
✨리뷰 멀티미디어 구현

### ISSUE THREAD

**Issue by mobzzzzz** [spartaKotlinTeamSober/wachu_server#41]
# 기능 설명
리뷰 멀티미디어 테이블을 구현하고 리뷰가 여러 장의 이미지를 가질 수 있게 합니다.
멀티미디어 테이블인 만큼 욕심이 생기면 유튜브 주소나 동영상을 저장할 수 있게 해보시는 것도 가능합니다

게시글 중간중간에 이미지를 넣는 부분은 우선 고려하지 않아도 됩니다. (wysiwyg editor)
최초 기획안대로 리뷰 내용 밑에 별도로 이미지 칸이 존재한다고 우선 가정하고
추후 추가 기능으로 구현을 고민해봅시다

# To-do
- [x] 리뷰 멀티미디어 정책 설정
- [x] 리뷰 멀티미디어 구현
- [x] 테스트 코드

# ETC
멀티미디어(이미지) ERD는 구현 레퍼런스가 꽤 많이 존재하니 적절히 자료를 찾아 구현을 추천드립니다.

예시:
![image](https://github.com/user-attachments/assets/3f221f47-ef8b-44b6-96fa-cdfccb24335d)

**Comment by npureaun** [comment]
테스트 코드 작성은 되었는데, multipartfile 이게 너무 빡셈.
