### ISSUE TITLE
✨와인 이미지 매칭

### ISSUE THREAD

**Issue by mobzzzzz** [spartaKotlinTeamSober/wachu_server#72]
# 기능 설명
S3에 미리 업로드해둔 무라벨 임시 와인 이미지들을 임의로 섞어서 API로 반환하기

# To-do
- [ ] 임시 와인 이미지 설정
- [ ] API 반환시 WineType 에 맞춰서 있는척 와인 이미지 보내주기

# ETC

**Comment by npureaun** [comment]
고정 url이니까 서버메모리로 가지고 있어도 나쁘지 않을거 같기도...?

**Comment by mobzzzzz** [comment]
와인 이미지는 아직 고정이긴하네요 유저 프로필 이미지만 Pre-signed 고려해봐도 될것같은 느낌

**Comment by npureaun** [comment]
![image](https://github.com/user-attachments/assets/adec773d-65ab-44af-b7be-299671adb577)
